### ISSUE TITLE
Working Groups

### ISSUE THREAD

**Issue by tedsuo** [opentracing/specification#101]
I would like to propose the formation of OpenTracing Working Groups to ensure that the project continues to develop quickly, in an open and transparent manner.

There are two initial groups proposals:
- Language Working Group https://github.com/opentracing/specification/pull/99
- Documentation Working Group https://github.com/opentracing/specification/pull/100

This is a tracking issue to discuss project structure in general. It will be updated to reflect current plans and proposals. Please comment on the individual proposals if you have questions and comments pertaining to their scope of work.

**Comment by griels** [comment]
Hi I'm interested in shaping the general API and the C/C++ and Python implementations.

**Comment by tedsuo** [comment]
Working groups have been created! Thank you to everyone who signed up.
