### ISSUE TITLE
Script to generate a PDF doc from Markdown

### ISSUE THREAD

**Issue by tappoz** [opentracing/specification#146]
## Problem

I was originally looking for a PDF doc on the website so I could read the spec offline.
I ended up generating a PDF myself, so I was thinking there could be an automated way to generate a PDF for these Markdown files.

## Proposal

Could we create a bash script with something like:

```sh
cat *.md | pandoc \
                    --variable geometry:a4paper \
                    --number-sections \
                    --pdf-engine=xelatex \
                    --toc \
                    -f markdown \
                    --listings \
                    -s \
                    -o opentracing-spec.pdf
```
Depending on the level of control this could be improved with LaTex directives, but the above should be enough for a basic PDF doc.

**Comment by yurishkuro** [comment]
no +1's or interest in this, apparently. Closing.
