### ISSUE TITLE
How to add baggage items to  Mongo DB operations using jaeger-cloud-starter in java

### ISSUE THREAD

**Issue by ArunaKumarik16** [opentracing/specification#152]

**Comment by ArunaKumarik16** [comment]
Please help me on this issue

**Comment by pavolloffay** [comment]
@ArunaKumarik16 please open an issue in https://github.com/opentracing-contrib/java-mongo-driver.

This is a specification and your request does not seem related to spec. Also `jaeger-cloud-starter` is just reusing the Mongo instrumentation.
