### ISSUE TITLE
Opentracing information in a message

### ISSUE THREAD

**Issue by venth** [opentracing/specification#153]
## Background
I model an asynchronous communication via Kafka using AsyncAPI specification and I’d like to describe there opentracing data to make the producing and consuming parties aware that such an information has to be supplied and could be consumed.

## Problem
I went through the specification and couldn’t find information about the message format.

## Questions to address
Please guide me to relevant part of the specification or provide the information about open tracing data structure I have to pass in a message.

**Comment by yurishkuro** [comment]
Working example with Kafka: https://github.com/PacktPublishing/Mastering-Distributed-Tracing/tree/master/Chapter05

**Comment by venth** [comment]
Thanks 👍
