### ISSUE TITLE
Introduce peer.address standard tag

### ISSUE THREAD

**Issue by bhs** [opentracing/specification#16]
Continuing the discussion from https://github.com/opentracing/opentracing.io/issues/116

cc: @yurishkuro @bensigelman @dkuebric @cwe1ss

**Comment by yurishkuro** [comment]
Renaming the issue since the general agreement in the previous discussion was for a more general `peer.address` tag, rather than `peer.hostPort`.  I'm +1 on that.

**Comment by wu-sheng** [comment]
Definitely +1 on that. I am doing like this in my tracer.

**Comment by bhs** [comment]
@yurishkuro @wu-sheng I put together https://github.com/opentracing/specification/pull/53 since this is such a small change.
