### ISSUE TITLE
me

### ISSUE THREAD

**Issue by adilhafeez** [opentracing/specification#160]
## Background
Something that gives context about why this is an issue.

## Problem
Describe the problem. If the issue is about an improvement you can skip this. If possible, include a description of the impact of the problem.

## Proposal
A proposal that, from your point of view, would solve the problem or improve the existing situation. It should also include the impact.

## Questions to address
Questions that should be answered as outcome of this issue.

**Comment by yurishkuro** [comment]
me too
![image](https://user-images.githubusercontent.com/3523016/124186737-bdd30f80-da8a-11eb-82ff-0b9166363e2e.png)

**Comment by adilhafeez** [comment]
oh how did that happen 😂
