### ISSUE TITLE
Invalid link to data_conventions.md

### ISSUE THREAD

**Issue by holmes1412** [opentracing/specification#161]
## Background
[data_conventions.md](https://github.com/opentracing/specification/blob/master/data_conventions.md) is invalid.

## Problem
In the following document,
https://github.com/opentracing/specification/blob/master/specification.md#the-big-picture-opentracings-scope ,
the link to `data modelling conventions`, while indicates https://github.com/opentracing/specification/blob/master/data_conventions.md
is 404 NOT FOUND. 

## Proposal
I found `data conventions`  in commit log. I guess maybe now it`s part of the [semantic_conventions.md](https://github.com/opentracing/specification/blob/master/semantic_conventions.md) ?

## Questions to address
 It would be appreciated if the invalid link could be fixed~

**Comment by yurishkuro** [comment]
Thanks for reporting.
