### ISSUE TITLE
Distributed context propagation as foundation for OpenTracing

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/specification#22]
Currently OpenTracing implements baggage as a feature on top of tracing. Rodrigo Fonseca proposed a different layered approach he calls "tracing plane" ([slides](https://docs.google.com/presentation/d/1ZMr1UsXJ0jms3dPWbO4E7cyhHbwClkWBGhJxtN8VrWs/)) where instrumentation and context propagation is done by the lower level, with distributed tracing being one of the higher order functions.

**Comment by bensigelman** [comment]
See also: #14 and https://github.com/opentracing/opentracing.io/issues/111

@yurishkuro arguably this issue is a dup, or vice versa. Thoughts?

**Comment by yurishkuro** [comment]
Indeed, closing in favor of #14
