### ISSUE TITLE
Duplicate

### ISSUE THREAD

**Issue by lookfwd** [opentracing/specification#28]
-

**Comment by lookfwd** [comment]
See also here: https://github.com/opentracing/opentracing.io/issues/66

**Comment by yurishkuro** [comment]
Duplicate of #9

**Comment by adriancole** [comment]
>
> Something like this would pave the way towards a more solid case for OT, where you can switch vendors without downtime since it allows a transition period (could be days) when both the old and the new versions are running. How do you guys handle migrations in general? As far as I can see, it should be close to impossible to switch without downtime.
>
> I think this approach will help upgrade or switch systems, though in
practice it might require complete deployment across the entire
architecture before you switch off the former.

Key concerns will be around aggregate (in and out of process) propagation
and trace context provisioning I think.
