### ISSUE TITLE
Is OpenTracing suitable for streaming/publish-subscribe systems?

### ISSUE THREAD

**Issue by OStrekalovsky** [opentracing/specification#38]
Suppose that there is a service A that emits some messages.
Another service B can subscribe to the messages from service A, process them and emits another messages. Another service C can subscribe to the messages from service B, process them and emits another messages and so on.
Could i use OpenTracing for tracing span that starts in service A and will be finished in probably another service(s) (where processing of source message may ends)?
It seems to be that OpenTracing was created only for request/response patterns and is not suitable for streaming of publish-subscribe systems. Isn't it?

**Comment by yurishkuro** [comment]
OpenTracing can be used with streaming / pub-sub. We have an internal project integrating tracing with Kafka, for example.

I think the main question is what you want to use tracing for in this scenario. For system analysis the lineage is often very important. With OpenTracing, we can correlate messages processed by different nodes in the pipeline and build an execution graph, similar to the call graph we get from regular RPC use case.

**Comment by OStrekalovsky** [comment]
And how we can handle situation when multiple services which consume the same source message want to finish started span which is single per message from source? Does any implementation of OpenTracing can handle this case?

**Comment by yurishkuro** [comment]
In our model the span does not represent the time message spends in the queue. Spans are meant to be single-process, so there is a span, started and finished, in the producer that encapsulates the work of putting the message into the queue. Each consumer starts its own span upon reading the message, and those spans encapsulate the work done by each consumer. You can think of it in terms of AWS's lambda architecture - a handler function does not even need to know how it gets the message, from a queue or via an RPC call, therefore its OpenTracing instrumentation should not be different in each scenario either.

**Comment by OStrekalovsky** [comment]
So that "short life spans" should be linked only by means of "FollowsFrom" reference type?

**Comment by yurishkuro** [comment]
FollowsFrom or yet another non-standard ref type. FollowsFrom ref type usually keeps the next span in the same trace. Sometimes you want the consumer to start a new trace, but link to the parent trace via some custom span ref type.

When spans are in the same trace, e.g. Zipkin will still display the total duration of the trace for you.
