### ISSUE TITLE
Rework the formal key and field guidance as an .md file

### ISSUE THREAD

**Issue by bhs** [opentracing/specification#41]
The .yaml file was a nice idea, but since there turns out to be language-specific logic (e.g., for errors). I think we should create an .md file to document these tags/fields, then make the yaml file really just the data (i.e., without comments and guidance on that front).

**Comment by wu-sheng** [comment]
In the guidance, I prefer to give some demonstrations in different scenarios. 

e.g. when access Database 
- ip=10.5.34.18
- port=3306 
- db_instance=consumers
- sql = select * from users where user_id = 1
- username = readonly_user

**Tags** should like this, assume I did instrumentation as a ORM framework developer:

|TAG_KEY|TAG_VALUE|COMMENTS|
|-------------|-------------|----|
| db.type | sql |
|db.instance| consumers|
|db.user|readonly_user|
|db.statement| select * from users where user_id = 1|
|peer.ipv4| 10.5.34.18|
|peer.port|3306|
|peer.service| jdbi/mysql/query| (Please ignore the name 😜)
|span.kind| client|
|component| spring jdbc template |

**Comment by wu-sheng** [comment]
Later this day, I can bring a new pull request about some .md , like `guidance/database/tags.md`.

In this guidance, provide some demonstrations about tag values, like `Spring JdbcTemplate -> MySQL`, `Jedis - > redis` etc.

**Comment by wu-sheng** [comment]
Crazy day.... But as I said before, bring you the db tag guidance. 😄

https://github.com/opentracing/specification/pull/44

**Comment by pavolloffay** [comment]
During the workshop when we were talking about versioning @cce mentioned that it is good that tags/logs are defined in `.yaml` because he can parse it based on a specific version.

I think there is some benefit to keep tag/log keys in `yaml`.

**Comment by wu-sheng** [comment]
@pavolloffay , Did @cce provide a tool? in which language platform? I think @bhs hope this happen, long time ago.

**Comment by cce** [comment]
At the workshop I was saying that if we kept the history of changes across versions in the yaml or machine-readable file somehow (e.g. when a name is changed / deprecated in favor of a new name), it would be easier for an automated tool to provide backwards compatibility. That was after someone mentioned concerns that updating the yaml file and removing old names could lead to confusion about changes and when / what version they occurred (unless you wrote a tool to look at the git history).

**Comment by bhs** [comment]
@cce @wu-sheng @pavolloffay I am in the midst of the PR. My plan is to move the bulk of the content (certainly detailed English writeups) into an `.md` file, but I will retain a `.yaml` file with nothing beyond the raw data. Or maybe one `.yaml` file for Span tags and one for log fields...

I also hope to address some of the confusion around the purpose of logging within OT! Maybe a separate PR, though. Hoping to get at least one of these out soon.

**Comment by bhs** [comment]
PTAL: https://github.com/opentracing/specification/pull/45
