### ISSUE TITLE
Clarify error "logs" as optional practice

### ISSUE THREAD

**Issue by adriancole** [opentracing/specification#47]
In the current data spec, it appears as though key/value logging is required to support logging:

https://github.com/opentracing/specification/blob/master/data_conventions.yaml#L127

According to @yurishkuro, this isn't quite the case:

> The minimum recommended level of marking errors (although I don't think it's explicitly written anywhere) is error: true tag , which seems to be supported by most implementations. I think it makes sense to state this more explicitly in the spec - (cc @bhs) - as part of describing "the semantics of transactions in distributed systems". Logging of the error is to provide additional (optional) information beyond the Boolean marker on the span. If instrumentation only logs the errors, I think it's incomplete. The fact that log(event: 'error') is called should not be interpreted by the tracer as "span has failed".

I think the spec should be adjusted and all contrib instrumentation updated to ensure KV logging isn't accidentally needed to support errors

**Comment by yurishkuro** [comment]
#46 already made this explicit.
