### ISSUE TITLE
Add an KEY CODE(integer value) for each tag/log-field key

### ISSUE THREAD

**Issue by wu-sheng** [opentracing/specification#50]
By so many acronyms or abbreviations existed in tags or log fields, I want to propose about adding an KEY CODE(integer value) for each key. e.g. db.instance keyCode=10; db.statement keyCode=11. Like other spec code, we can retain some code(0-10000) for OT official keys.

After we have these, all platform implementations, can use the integer to judge. In my tracer implementations, we have an analysis backend, analysis the service-flow by some tags, right now, it must be based on String.equal() and consider char-case... I hope we can improve on that.

@bhs @objectiser thoughts?

**Comment by yurishkuro** [comment]
@wu-sheng It's not clear what you mean by "adding" key code. Are you suggesting replacing string tag keys with numeric values?

**Comment by wu-sheng** [comment]
I am not sure replacing is good enough. In my deep mind, I hope to replace it. Hope we can discuss on that. 

By adding, it means maybe, just maybe, `TagKey` is a class, with two fields, `name` and `code`.

**Comment by yurishkuro** [comment]
That would still require an API change, since the methods currently accept a string as a key. And we always want to keep the API open to people using arbitrary strings for their own tags.

Personally I am not in favor of maintaining such numeric enums. Does string comparison really have such impact on performance?

**Comment by wu-sheng** [comment]
Closing this, find a way to avoid performance issue of string compare.
