### ISSUE TITLE
Component hostname

### ISSUE THREAD

**Issue by gkumar7** [opentracing/specification#60]
After going through the changes in the specification for tags, I noticed there is no tag defined for the hostname of the component which generated the span? There is a ```component``` tag, but something like ```component.hostname``` would be useful.

**Comment by yurishkuro** [comment]
(a) the host name of the component is not different from the host name of the overall application / tracer, and (b) it does not changes between spans. Therefore it can be implicitly captured by the tracer, it does not need to be provided by instrumentation over and over.

**Comment by wu-sheng** [comment]
Agree @yurishkuro 

@gkumar7 , `hostname` of local `component` is the info about this machine, tracer can get that without span. And if you `component` means something remote, like database or remote service, its hostname is provided by `peer.*`

**Comment by gkumar7** [comment]
Thank you for the clarification!
